name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run Prisma migrations
        working-directory: ./backend
        env:
          DATABASE_URL: file:./test.db
        run: npx prisma migrate dev --name ci_test

      - name: Run backend tests
        working-directory: ./backend
        env:
          DATABASE_URL: file:./test.db
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm test

      - name: Build backend
        working-directory: ./backend
        run: npm run build

  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker images
        run: docker compose build

      - name: Test Docker stack
        run: |
          docker compose up -d
          sleep 10
          curl -f http://localhost:4000/health || exit 1
          docker compose down